services:
  geth: # this is Optimism's geth client
    build: .
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    command:
      - ./geth-entrypoint.sh
    environment:
      - OP_GETH_GENESIS_FILE_PATH=goerli/genesis-l2.json
      - OP_GETH_SEQUENCER_HTTP=https://goerli.base.org
      - OP_NODE_L2_ENGINE_AUTH=/tmp/engine-auth-jwt
      - OP_NODE_L2_ENGINE_AUTH_RAW=688f5d737bad920bdfb2fc2f488d6b6209eebda1dae949a8de91398d932c517a # for localdev only
  node:
    build: .
    depends_on:
      - geth
    ports:
      - 7545:8545
      - 9222:9222
      - 7300:7300 # metrics
      - 6060:6060
    command:
      - ./op-node-entrypoint.sh
    environment:
      - OP_NODE_L1_ETH_RPC=$ethRpc # [recommended] replace with your preferred L1 (ethereum, not Base) node RPC URL
      - OP_NODE_L1_TRUST_RPC=true # temporary for Goerli Shapella upgrade
      - OP_NODE_L2_ENGINE_AUTH=/tmp/engine-auth-jwt
      - OP_NODE_L2_ENGINE_AUTH_RAW=688f5d737bad920bdfb2fc2f488d6b6209eebda1dae949a8de91398d932c517a # for localdev only
      - OP_NODE_L2_ENGINE_RPC=http://geth:8551
      - OP_NODE_LOG_LEVEL=info
      - OP_NODE_METRICS_ADDR=0.0.0.0
      - OP_NODE_METRICS_ENABLED=true
      - OP_NODE_METRICS_PORT=7300
      - OP_NODE_P2P_AGENT=base
      - OP_NODE_P2P_BOOTNODES=enr:-J64QBbwPjPLZ6IOOToOLsSjtFUjjzN66qmBZdUexpO32Klrc458Q24kbty2PdRaLacHM5z-cZQr8mjeQu3pik6jPSOGAYYFIqBfgmlkgnY0gmlwhDaRWFWHb3BzdGFja4SzlAUAiXNlY3AyNTZrMaECmeSnJh7zjKrDSPo>      - OP_NODE_P2P_LISTEN_IP=0.0.0.0
      - OP_NODE_P2P_LISTEN_TCP_PORT=9222
      - OP_NODE_P2P_LISTEN_UDP_PORT=9222
      - OP_NODE_ROLLUP_CONFIG=goerli/rollup.json
      - OP_NODE_RPC_ADDR=0.0.0.0
      - OP_NODE_RPC_PORT=8545
      - OP_NODE_SNAPSHOT_LOG=/tmp/op-node-snapshot-log
      - OP_NODE_VERIFIER_L1_CONFS=0
